### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by champagnekapy** [champagnekapy/skupina_4#2]
Create nav bar component with links to:
-Home
-Catalog
-Crazy8Game
-About us

and log in on the right side-->see example photo
![image](https://user-images.githubusercontent.com/24227274/222927075-db40c6be-05da-4aae-ab6e-533ba722b08b.png)

**Comment by champagnekapy** [comment]
Replace `<a href="/" >...</a>` with `<a href="/" <Link to="/">...</Link>`

**Comment by vukmilenkovic** [comment]
Resolved
