### ISSUE TITLE
Home page layout

### ISSUE THREAD

**Issue by champagnekapy** [champagnekapy/skupina_4#6]
Create home page layout with mui grid component. Layout has to fit one tic-tac-toe game on top, best selling items on right and sugested items uder the tic tac toe game. 

MUI Grid documentation: https://mui.com/material-ui/react-grid/

Example:
![image](https://user-images.githubusercontent.com/24227274/222928872-571c2627-110c-4470-9775-c8da18980ca1.png)

**Comment by cvetkoalen** [comment]
Resolved
