### ISSUE TITLE
Cart component

### ISSUE THREAD

**Issue by champagnekapy** [champagnekapy/skupina_4#9]
Create cart component (only a placeholder page with CHECKOUT button) and Checkout component.

Cart example:
![image](https://user-images.githubusercontent.com/24227274/222928510-0c83997d-9cb0-40c3-afa3-6fe8a035e992.png)

Checkout page should be built with [FORM](https://www.w3schools.com/html/html_forms.asp)

Checkout example:
![image](https://user-images.githubusercontent.com/24227274/222928537-34064e77-fc8e-4a73-bf1c-60ac69a4095a.png)

**Comment by Pinky1256461** [comment]
Resolved.
